- name: chaniging in /etc/profile file 
  block:
    - name:  using ssh timeout 
      blockinfile: 
        path: /etc/profile  
        insertafter: EOF 
        backup: yes
        state: present
        block: |
          "#It is a test block which is added by Ansible automation"
          export TMOUT=900 

    - name: setting the umask 
      lineinfile:
        path: /etc/profile 
        regex: "^umask"
        line: "umask 0077"
        state: present
