- name:  Creating group
  group:
    name: cloudadmins
    gid: 3000
    state: present
- name:  Creating users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.id }}"
    state: present
    groups: cloudadmins,wheel
    generate_ssh_key: yes
  loop: "{{ user }}"
- name: Setting the authorized key taken from the file
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
  loop: "{{ user }}"
